import assert from 'node:assert/strict';
import http from 'node:http';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { createHandler, resolveClientAddress } from '../src/app.js';
import { BoardProvider } from '../src/board/board-provider.js';
import { TrelloProvider, BoardConfigurationError } from '../src/board/trello-provider.js';
import { formatDigest, runDigest } from '../src/digest/weekly-digest.js';
import { MemoryRateLimit } from '../src/rate-limit/rate-limit.js';
import { createFeedbackController, loadRecaptchaScript } from '../../assets/feedback.js';

class FakeBoard extends BoardProvider { constructor() { super(); this.items = []; this.counts = { total: 0, categories: {} }; } async createFeedback(value) { this.items.push(value); } async countNewFeedbackSince() { return this.counts; } }
class FakeCaptcha { constructor(valid = true) { this.valid = valid; } async verify() { return this.valid; } }
const config = (enabled, trustProxy = false) => ({ trustProxy, captcha: { provider: 'recaptcha', enabled, siteKey: 'public-site-key' } });
async function fixture({ captcha = false, validCaptcha = true, board = new FakeBoard(), max = 50, trustProxy = false, logger = { error() {} } } = {}) {
  const server = http.createServer(createHandler({ config: config(captcha, trustProxy), boardProvider: board, captchaProvider: new FakeCaptcha(validCaptcha), rateLimit: new MemoryRateLimit({ max, windowMs: 60000 }), logger }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  return { board, close: () => new Promise(resolve => server.close(resolve)), request: (path, options) => fetch(base + path, options) };
}
const valid = { category: 'Awareness', feedback: 'A useful message', replyEmail: 'reply@example.invalid', captchaToken: 'test-token', honeypot: '', ignored: 'not forwarded' };
const post = body => ({ method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });

test('healthz = 200', async t => { const f = await fixture(); t.after(f.close); assert.equal((await f.request('/healthz')).status, 200); });
test('config exposes public values and no secret', async t => { const f = await fixture({ captcha: true }); t.after(f.close); const body = await (await f.request('/api/feedback/config')).json(); assert.deepEqual(body, { captcha: { provider: 'recaptcha', enabled: true, siteKey: 'public-site-key' } }); assert.equal(JSON.stringify(body).includes('secret'), false); });
test('valid feedback succeeds once', async t => { const f = await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback', post(valid))).status, 201); assert.equal(f.board.items.length, 1); });
for (const [name, patch] of [['empty category',{category:''}],['unknown category',{category:'Unknown'}],['empty feedback',{feedback:''}],['long feedback',{feedback:'x'.repeat(10001)}],['invalid email',{replyEmail:'bad'}]]) test(`${name} = 400`, async t => { const f=await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback',post({...valid,...patch}))).status,400); });
test('honeypot is neutral and never writes', async t => { const f=await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback',post({...valid,honeypot:'bot'}))).status,201); assert.equal(f.board.items.length,0); });
test('missing captcha = 400', async t => { const f=await fixture({captcha:true}); t.after(f.close); assert.equal((await f.request('/api/feedback',post({...valid,captchaToken:''}))).status,400); });
test('invalid captcha = 400', async t => { const f=await fixture({captcha:true,validCaptcha:false}); t.after(f.close); assert.equal((await f.request('/api/feedback',post(valid))).status,400); });
test('valid captcha writes', async t => { const f=await fixture({captcha:true}); t.after(f.close); await f.request('/api/feedback',post(valid)); assert.equal(f.board.items.length,1); });
test('board error is controlled 503 without stack', async t => { const board={async createFeedback(){throw new Error('internal-sensitive-detail')}}; const f=await fixture({board}); t.after(f.close); const r=await f.request('/api/feedback',post(valid)); const text=await r.text(); assert.equal(r.status,503); assert.equal(text.includes('internal-sensitive-detail'),false); assert.equal(text.includes(' at '),false); });
test('rate limit = 429', async t => { const f=await fixture({max:1}); t.after(f.close); await f.request('/api/feedback',post(valid)); assert.equal((await f.request('/api/feedback',post(valid))).status,429); });
test('large body = 413', async t => { const f=await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback',post({...valid,feedback:'x'.repeat(33000)}))).status,413); });
test('GET submit endpoint = 405', async t => { const f=await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback')).status,405); });
test('wrong content type = 415', async t => { const f=await fixture(); t.after(f.close); assert.equal((await f.request('/api/feedback',{method:'POST',body:'x'})).status,415); });
test('payload excludes captcha, IP and unknown fields', async t => { const f=await fixture(); t.after(f.close); await f.request('/api/feedback',post(valid)); const item=f.board.items[0]; assert.deepEqual(Object.keys(item).sort(),['category','feedback','receivedAt','replyEmail','requestId']); assert.equal(JSON.stringify(item).includes('test-token'),false); assert.equal(JSON.stringify(item).includes('127.0.0.1'),false); assert.equal(JSON.stringify(item).includes('ignored'),false); });
test('trustProxy false ignores forged X-Real-IP and uses socket address', () => { const req={headers:{'x-real-ip':'198.51.100.9'},socket:{remoteAddress:'127.0.0.1'}}; assert.equal(resolveClientAddress(req,false),'127.0.0.1'); });
test('trustProxy true uses valid X-Real-IP', () => { const req={headers:{'x-real-ip':'198.51.100.9'},socket:{remoteAddress:'127.0.0.1'}}; assert.equal(resolveClientAddress(req,true),'198.51.100.9'); });
test('trustProxy true falls back for missing header', () => { assert.equal(resolveClientAddress({headers:{},socket:{remoteAddress:'127.0.0.1'}},true),'127.0.0.1'); });
test('trustProxy true rejects invalid or chained header', () => { for (const value of ['not-an-ip','198.51.100.9, 203.0.113.4','']) assert.equal(resolveClientAddress({headers:{'x-real-ip':value},socket:{remoteAddress:'127.0.0.1'}},true),'127.0.0.1'); });
test('trusted proxy rate limit separates client addresses', async t => { const f=await fixture({max:1,trustProxy:true}); t.after(f.close); assert.equal((await f.request('/api/feedback',{...post(valid),headers:{...post(valid).headers,'x-real-ip':'198.51.100.1'}})).status,201); assert.equal((await f.request('/api/feedback',{...post(valid),headers:{...post(valid).headers,'x-real-ip':'198.51.100.2'}})).status,201); });
test('trusted proxy rate limit still limits same client address', async t => { const f=await fixture({max:1,trustProxy:true}); t.after(f.close); const options={...post(valid),headers:{...post(valid).headers,'x-real-ip':'198.51.100.3'}}; await f.request('/api/feedback',options); assert.equal((await f.request('/api/feedback',options)).status,429); });
test('expired rate-limit entries are removed', () => { let now=0; const limiter=new MemoryRateLimit({max:2,windowMs:10,now:()=>now}); limiter.allow('old'); assert.equal(limiter.entries.has('old'),true); now=11; limiter.allow('new'); assert.equal(limiter.entries.has('old'),false); assert.equal(limiter.entries.has('new'),true); });
test('client address never appears in logs', async t => { const logs=[]; const board={async createFeedback(){throw new Error('fail')}}; const f=await fixture({board,trustProxy:true,logger:{error(value){logs.push(value)}}}); t.after(f.close); await f.request('/api/feedback',{...post(valid),headers:{...post(valid).headers,'x-real-ip':'198.51.100.44'}}); assert.equal(JSON.stringify(logs).includes('198.51.100.44'),false); });
test('client address is not passed to captcha', async t => { let args; const captchaProvider={async verify(...value){args=value;return true}}; const board=new FakeBoard(); const server=http.createServer(createHandler({config:config(true,true),boardProvider:board,captchaProvider,rateLimit:new MemoryRateLimit({max:5,windowMs:60000}),logger:{error(){}}})); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); t.after(()=>new Promise(resolve=>server.close(resolve))); await fetch(`http://127.0.0.1:${server.address().port}/api/feedback`,{...post(valid),headers:{...post(valid).headers,'x-real-ip':'198.51.100.45'}}); assert.deepEqual(args,['test-token']); assert.equal(JSON.stringify(board.items).includes('198.51.100.45'),false); });

const trelloConfig = () => ({ apiKey:'key', token:'token', categoryDestinations:{Einlass:'list-e',Bar:'list-b',Club:'list-c',Awareness:'list-a',Sonstiges:'list-s'},openLabelId:'open',replyRequestedLabelId:'reply' });
for (const [category,id] of Object.entries(trelloConfig().categoryDestinations)) test(`${category} maps to category destination`, async () => { let body; const p=new TrelloProvider(trelloConfig(),async(_u,o)=>{body=o.body;return{ok:true}}); await p.createFeedback({category,feedback:'text',replyEmail:'',receivedAt:'2026-08-12T09:15:00Z'}); assert.equal(body.get('idList'),id); });
test('every card gets open label', async () => { let body; const p=new TrelloProvider(trelloConfig(),async(_u,o)=>{body=o.body;return{ok:true}}); await p.createFeedback({category:'Bar',feedback:'text',replyEmail:'',receivedAt:new Date().toISOString()}); assert.equal(body.get('idLabels'),'open'); });
test('reply email adds reply label', async () => { let body; const p=new TrelloProvider(trelloConfig(),async(_u,o)=>{body=o.body;return{ok:true}}); await p.createFeedback({category:'Bar',feedback:'text',replyEmail:'a@example.invalid',receivedAt:new Date().toISOString()}); assert.equal(body.get('idLabels'),'open,reply'); });
test('missing destination is controlled configuration error', async () => { const c=trelloConfig(); c.categoryDestinations.Bar=''; await assert.rejects(()=>new TrelloProvider(c).createFeedback({category:'Bar',feedback:'x',replyEmail:'',receivedAt:new Date().toISOString()}),BoardConfigurationError); });
test('missing open label is controlled configuration error', async () => { const c=trelloConfig(); c.openLabelId=''; await assert.rejects(()=>new TrelloProvider(c).createFeedback({category:'Bar',feedback:'x',replyEmail:'',receivedAt:new Date().toISOString()}),BoardConfigurationError); });
test('card description has no Gmail subject', async () => { let body; const p=new TrelloProvider(trelloConfig(),async(_u,o)=>{body=o.body;return{ok:true}}); await p.createFeedback({category:'Club',feedback:'hello',replyEmail:'',receivedAt:new Date().toISOString()}); assert.equal(body.get('desc').includes('Gmail'),false); assert.match(body.get('name'),/^Website Feedback · Club ·/); });
test('fake provider is interchangeable', async () => { const fake=new FakeBoard(); await fake.createFeedback({category:'Bar'}); assert.equal(fake.items.length,1); });
test('digest skips zero', async () => { const board=new FakeBoard(); const result=await runDigest({boardProvider:board,mailProvider:{send(){throw new Error()}},since:'x',recipient:'x'}); assert.equal(result.sent,false); });
test('digest aggregates categories without personal content', async () => { const board=new FakeBoard(); board.counts={total:3,categories:{Einlass:1,Awareness:2}}; let mail; await runDigest({boardProvider:board,mailProvider:{async send(v){mail=v}},since:'x',recipient:'team@example.invalid'}); assert.match(mail.text,/Einlass: 1/); assert.match(mail.text,/Awareness: 2/); assert.equal(mail.text.includes('reply@example.invalid'),false); assert.equal(mail.text.includes('A useful message'),false); });
test('digest formatter is provider neutral', () => { assert.equal(formatDigest({total:1,categories:{Bar:1}}).includes('Trello'),false); });
test('frontend removed FormSubmit, private target and external next', async () => { const html=await readFile(new URL('../../feedback.html',import.meta.url),'utf8'); assert.equal(/formsubmit|teuber1995|_next|github\.io/i.test(html),false); });
test('frontend redirects locally and prevents duplicate submit', async () => { const js=await readFile(new URL('../../assets/feedback.js',import.meta.url),'utf8'); assert.match(js,/feedback-thanks\.html/); assert.match(js,/button\.disabled/); assert.match(js,/Feedback could not be sent/); });

function frontendFixture({ configValue={captcha:{enabled:false,provider:'recaptcha',siteKey:''}}, configOk=true, configJsonError=false, postOk=true, loadError=false }={}) {
  const listeners={};
  const form={elements:{category:{value:'Awareness'},feedback:{value:'A useful message'},replyEmail:{value:'reply@example.invalid'},honeypot:{value:''}},addEventListener(type,handler){listeners[type]=handler}};
  const status={textContent:''}; const button={disabled:false}; const captchaContainer={};
  const requests=[]; const renders=[]; const resets=[]; let widgetOptions; let redirected=''; let loadCalls=0;
  const grecaptcha={render(container,options){renders.push(container);widgetOptions=options;return 17},reset(id){resets.push(id)}};
  const fetchImpl=async (url,options) => { requests.push({url,options}); if(url.endsWith('/config')) return {ok:configOk,json:async()=>{if(configJsonError)throw new Error('bad json');return configValue}}; return {ok:postOk}; };
  const controller=createFeedbackController({form,status,button,captchaContainer,fetchImpl,loadCaptcha:async()=>{loadCalls++;if(loadError)throw new Error('load');return grecaptcha},redirect:url=>{redirected=url}});
  return {controller,form,status,button,captchaContainer,requests,renders,resets,grecaptcha,listeners,get widgetOptions(){return widgetOptions},get redirected(){return redirected},get loadCalls(){return loadCalls}};
}

test('frontend: captcha disabled enables submit without loading Google', async()=>{const f=frontendFixture();await f.controller.initialise();assert.equal(f.button.disabled,false);assert.equal(f.loadCalls,0)});
test('frontend: captcha enabled loads and renders explicit widget', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'public-key'}}});await f.controller.initialise();assert.equal(f.loadCalls,1);assert.equal(f.renders.length,1);assert.equal(f.widgetOptions.sitekey,'public-key');assert.equal(f.button.disabled,false)});
test('frontend: unknown captcha provider is blocked without Google', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'other',siteKey:'key'}}});await f.controller.initialise();assert.equal(f.button.disabled,true);assert.equal(f.loadCalls,0);assert.equal(f.status.textContent,'Spam protection is currently unavailable.')});
test('frontend: enabled captcha with empty site key is blocked', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:' '}}});await f.controller.initialise();assert.equal(f.button.disabled,true);assert.match(f.status.textContent,/not configured/);assert.equal(f.loadCalls,0)});
test('frontend: unavailable config keeps submit blocked', async()=>{const f=frontendFixture({configOk:false});await f.controller.initialise();assert.equal(f.button.disabled,true);assert.match(f.status.textContent,/configuration is currently unavailable/)});
test('frontend: invalid config keeps submit blocked', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:'no'}}});await f.controller.initialise();assert.equal(f.button.disabled,true);assert.match(f.status.textContent,/configuration is currently unavailable/)});
test('frontend: reCAPTCHA load failure is visible and blocked', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}},loadError:true});await f.controller.initialise();assert.equal(f.button.disabled,true);assert.match(f.status.textContent,/configuration is currently unavailable/)});
test('frontend: success callback stores captcha token without logging it', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}}});await f.controller.initialise();f.widgetOptions.callback('captcha-secret');assert.equal(f.controller.getState().captchaToken,'captcha-secret');assert.equal(f.status.textContent,'')});
test('frontend: expired callback clears captcha token', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}}});await f.controller.initialise();f.widgetOptions.callback('token');f.widgetOptions['expired-callback']();assert.equal(f.controller.getState().captchaToken,'');assert.match(f.status.textContent,/expired/)});
test('frontend: error callback clears token and shows controlled error', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}}});await f.controller.initialise();f.widgetOptions.callback('token');f.widgetOptions['error-callback']();assert.equal(f.controller.getState().captchaToken,'');assert.equal(f.status.textContent,'Spam protection is currently unavailable.')});
test('frontend: enabled captcha without token never posts', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}}});await f.controller.initialise();await f.controller.submit({preventDefault(){}});assert.equal(f.requests.length,1);assert.match(f.status.textContent,/complete the spam protection/)});
test('frontend: disabled captcha posts exact payload with empty token', async()=>{const f=frontendFixture();await f.controller.initialise();await f.controller.submit({preventDefault(){}});const body=JSON.parse(f.requests[1].options.body);assert.deepEqual(body,{category:'Awareness',feedback:'A useful message',replyEmail:'reply@example.invalid',honeypot:'',captchaToken:''})});
test('frontend: enabled captcha posts exact payload with callback token', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}}});await f.controller.initialise();f.widgetOptions.callback('valid-token');await f.controller.submit({preventDefault(){}});const body=JSON.parse(f.requests[1].options.body);assert.equal(body.captchaToken,'valid-token');assert.deepEqual(Object.keys(body).sort(),['captchaToken','category','feedback','honeypot','replyEmail'])});
test('frontend: failed API resets widget and requires a new token', async()=>{const f=frontendFixture({configValue:{captcha:{enabled:true,provider:'recaptcha',siteKey:'key'}},postOk:false});await f.controller.initialise();f.widgetOptions.callback('one-use-token');await f.controller.submit({preventDefault(){}});assert.deepEqual(f.resets,[17]);assert.equal(f.controller.getState().captchaToken,'');assert.equal(f.button.disabled,false)});
test('frontend: successful API redirects to local thanks page', async()=>{const f=frontendFixture();await f.controller.initialise();await f.controller.submit({preventDefault(){}});assert.equal(f.redirected,'feedback-thanks.html')});
test('frontend: reCAPTCHA loader appends Google script only once', async()=>{const listeners={};let appended=0;const script={addEventListener(type,handler){listeners[type]=handler}};const documentObject={querySelector(){return null},createElement(){return script},head:{append(){appended++}}};const windowObject={};const first=loadRecaptchaScript(documentObject,windowObject);const second=loadRecaptchaScript(documentObject,windowObject);windowObject.grecaptcha={render(){}};listeners.load();assert.equal(await first,windowObject.grecaptcha);assert.equal(await second,windowObject.grecaptcha);assert.equal(appended,1)});
