name: Archived admin event filter migration

on:
  workflow_dispatch:

jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The admin event filter migration has already been completed."
