name: Archived one-time RA artist separator task

on:
  workflow_dispatch:

jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The RA artist separator migration has already been completed."
